### ISSUE TITLE
Future for pyfreqpm

### ISSUE THREAD

**Issue by DJuego** [smirnov-am/pyfreqpm#1]
This project seems very promising. Thank you for your efforts!

In general, I am a C/C++ developer but i use Python for fast prototyping. I want to ask you if you have any plan or schedule for **pyfreqpm**. It seems you will develop the maxminer algorythm. Do you think to implement other Frequent Pattern mining algorithms? Thanks again!

DJuego

**Comment by smirnov-am** [comment]
Hello DJiuego
I have no plan to work further on this repo. It's just a remnant of a failed startup

**Comment by DJuego** [comment]
I've suspected that for a long time. :-D But thank you very much for responding officially.
DJuego
